---
- hosts: all
  become: yes
  tasks:
  -  name: install apache2 on node server
     apt: 
      name: apache2
      state: present

  -  name: I want to start webserver on ansible ubuntu node
     services:
      name: apache2
      state: started 